# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: SwizlyPeasy.Gateway CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  CI_Pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Start Multi Containers
      run: docker-compose -f Test/SwizlyPeasy.Test.IntegrationTest/Docker/docker-compose.yml -f Test/SwizlyPeasy.Test.IntegrationTest/Docker/docker-compose.override.yml up -d
    - name: Sleep for 20 seconds
      run: sleep 20s
      shell: bash
    - name: Restore dependencies
      run: dotnet restore SwizlyPeasy.Gateway.sln
    - name: Build
      run: dotnet build --no-restore SwizlyPeasy.Gateway.sln
    - name: Unit & Integration Test
      run: dotnet test --no-build SwizlyPeasy.Gateway.sln /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=opencover
    - name: Rename paths in coverage file (Unit Tests)
      run: sed -i 's|/home/runner/work/SwizlyPeasy.Gateway/SwizlyPeasy.Gateway|/github/workspace|g' /home/runner/work/SwizlyPeasy.Gateway/SwizlyPeasy.Gateway/Test/SwizlyPeasy.Test.UnitTest/TestResults/coverage.opencover.xml
    - name: Rename paths in coverage file (Integration Test)
      run: sed -i 's|/home/runner/work/SwizlyPeasy.Gateway/SwizlyPeasy.Gateway|/github/workspace|g' /home/runner/work/SwizlyPeasy.Gateway/SwizlyPeasy.Gateway/Test/SwizlyPeasy.Test.IntegrationTest/TestResults/coverage.opencover.xml
    - name: SonarScanner for .NET 8 with pull request decoration support
      uses: highbyte/sonarscan-dotnet@v2.3.1
      with:
        sonarProjectKey: ggnaegi_SwizlyPeasy.Gateway
        sonarProjectName:  SwizlyPeasy.Gateway
        sonarOrganization: ggnaegi
        dotnetBuildArguments: SwizlyPeasy.Gateway.sln
        dotnetDisableTests: true
        sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/*.opencover.xml" /d:sonar.verbose=true /d:sonar.scm.exclusions.disabled=true /d:sonar.coverage.exclusions="**Test*.cs"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
