name: SwizlyPeasy.Gateway Nugets

on:
  release:
    types: [published]

jobs:
  Build_Nuget_Packages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore SwizlyPeasy.Gateway.sln
    - name: Build
      run: dotnet build --no-restore SwizlyPeasy.Gateway.sln -c Release
    - name: Pack SwizlyPeasy.Common
      run: dotnet pack -c Release SwizlyPeasy.Common/SwizlyPeasy.Common.csproj --no-build --output .
    - name: Pack SwizlyPeasy.Consul
      run: dotnet pack -c Release SwizlyPeasy.Consul/SwizlyPeasy.Consul.csproj --no-build --output .
    - name: Pack SwizlyPeasy.Gateway
      run: dotnet pack -c Release SwizlyPeasy.Gateway/SwizlyPeasy.Gateway.csproj --no-build --output .
    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --api-key NUGET_TOKEN --source https://api.nuget.org/v3/index.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        NUGET_TOKEN: ${{ secrets.NUGET_API_KEY }}
      
